version: '3'
services:
  db:
    image: mongo:4.0
    volumes:
      - ./db/data/db:/data/db
    ports:
      - 27017:27017
  app:
    image: node:10.15
    volumes:
      - ./:/code
    command: npm start --prefix /code
    ports:
      - 3000:3000